USE master
GO

CREATE DATABASE LAWBD
GO

USE LAWBD
GO

BEGIN TRANSACTION

CREATE TABLE UTILIZADOR (
	ID INT NOT NULL IDENTITY(1,1), 
	NOME VARCHAR(128) NOT NULL,
	USERNAME VARCHAR(32) NOT NULL,
	EMAIL VARCHAR(32) NOT NULL,
	PASSWD VARCHAR(128) NOT NULL, -- PASSWORD HASHED
	DATA_ATIVACAO DATE, -- CONTA ATIVADA (EMAIL) EM QUE DATA?
	ANOTACOES VARCHAR(1024) NOT NULL,
	PRIMARY KEY (ID)
	)

CREATE TABLE LEITOR (
	ID INT NOT NULL,
	CONTACTO VARCHAR(16), -- NÚMERO DE TELEMÓVEL TUGA = 13 CHARS C/ +351
	MORADA VARCHAR(128),
	FOREIGN KEY (ID) REFERENCES UTILIZADOR
	)	

CREATE TABLE BIBLEOTECARIO (
	ID INT NOT NULL,
	CONTACTO VARCHAR(16),
	DATA_ATIVACAO DATE,
	ADMIN_ATIVACAO INT,
	FOREIGN KEY (ID) REFERENCES UTILIZADOR
	)

CREATE TABLE ADMINISTRADOR (
	ID INT NOT NULL,
	ID_CRIADOR INT NOT NULL,
	DATA_CRIACAO DATE NOT NULL,
	FOREIGN KEY (ID) REFERENCES UTILIZADOR,
	-- FOREIGN KEY (ID_CRIADOR) REFERENCES UTILIZADOR
	)

CREATE TABLE BLOQUEIA (
	ID INT NOT NULL IDENTITY(1,1),
	USERID INT NOT NULL,
	ADMINID INT NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_FIM DATE,
	MOTIVO VARCHAR(1024),
	PRIMARY KEY (ID),
	FOREIGN KEY (USERID) REFERENCES UTILIZADOR	
	)

CREATE TABLE NOTIFICACOES (
	ID INT NOT NULL IDENTITY(1,1),
	USERID INT NOT NULL,
	TIPO INT NOT NULL,
	CONTENT VARCHAR(512) NOT NULL,
	DATA_GEN DATE NOT NULL,
	DATA_READ DATE,
	PRIMARY KEY (ID),
	FOREIGN KEY (USERID) REFERENCES UTILIZADOR
	)

CREATE TABLE BIBLIOTECA (
	ID INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(32) NOT NULL,
	LOCALIZACAO VARCHAR(128) NOT NULL,
	EMAIL VARCHAR(32) NOT NULL,
	TELEFONE VARCHAR(16) NOT NULL,
	HORARIO VARCHAR(256) NOT NULL,
	PRIMARY KEY (ID)
	)

CREATE TABLE EDITOR (
	ID INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(128) NOT NULL,
	FOTO VARCHAR(256),
	DESCRICAO VARCHAR(1024),
	PRIMARY KEY (ID)
	)


CREATE TABLE EDICAO_LIVRO (
	ISBN VARCHAR(13) NOT NULL,
	TITULO VARCHAR(64) NOT NULL,
	SINOPSE VARCHAR(1024) NOT NULL,
	CAPA VARCHAR(256), -- FILENAME DA IMAGEM
	IDIOMA VARCHAR(2), -- ISO 639 LANGUAGE CODES 
	DESCFISICA VARCHAR(256), -- TAMANHO, CAPA DURA, ETC
	ID_EDITOR INT NOT NULL,
	DATA_PUB DATE NOT NULL,
	PRIMARY KEY (ISBN),
	)

CREATE TABLE AUTOR (
	ID INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(128) NOT NULL,
	FOTO VARCHAR(256),
	DESCRICAO VARCHAR(1024),
	PRIMARY KEY (ID)
	)

CREATE TABLE GENERO (
	ID INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(128) NOT NULL,
	PRIMARY KEY (ID)
	)

CREATE TABLE AUTORES_LIVROS (
	ISBN VARCHAR(13) NOT NULL,
	ID_AUTOR INT NOT NULL,
	FOREIGN KEY (ISBN) REFERENCES EDICAO_LIVRO,
	FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR
	)

CREATE TABLE GENEROS_LIVROS (
	ISBN VARCHAR(13) NOT NULL,
	ID_GENERO INT NOT NULL,
	FOREIGN KEY (ISBN) REFERENCES EDICAO_LIVRO,
	FOREIGN KEY (ID_GENERO) REFERENCES GENERO
	)



CREATE TABLE UNIT_LIVRO (
	ISBN VARCHAR(13) NOT NULL,
	ID INT NOT NULL IDENTITY(1,1),
	ESTADO VARCHAR(512), -- COMO ESTÁ O LIVRO FISICAMENTE, VISÍVEL NA PLATAFORMA?
	PRECO_AQUISICAO FLOAT,
	DATA_AQUISICAO DATE,
	REQUISITADO BIT NOT NULL, 
	ANOTACOES VARCHAR(1024) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ISBN) REFERENCES EDICAO_LIVRO
	)

CREATE TABLE EMPRESTIMO (
	ID INT NOT NULL IDENTITY(1,1),
	LEITOR INT NOT NULL,
	ID_LIVRO INT NOT NULL,
	DATA_REQ DATE NOT NULL, -- NO SITE
	DATA_LEV DATE NOT NULL, -- FISICAMENTE
	DATA_LIM DATE NOT NULL, -- DATA ATÉ TER DE DEVOLVER
	BIBLIOTECARIO_LEV INT NOT NULL, -- QUEM ENTREGOU O LIVRO
	DATA_ENTR DATE, -- DATA DE ENTREGA
	BIBLIOTECARIO_ENTR INT, -- QUEM RECEBEU O LIVRO
	PRIMARY KEY (ID, DATA_REQ),
	FOREIGN KEY (ID_LIVRO) REFERENCES UNIT_LIVRO,
	FOREIGN KEY (LEITOR) REFERENCES UTILIZADOR, 
)

CREATE TABLE COMMENT (
	ID INT NOT NULL IDENTITY(1,1), 
	LEITOR INT NOT NULL,
	LIVRO VARCHAR(13) NOT NULL,
	TEXTO VARCHAR(1024) NOT NULL,
	DATA_POST DATE NOT NULL,
	NOTA INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (LIVRO) REFERENCES EDICAO_LIVRO,
	FOREIGN KEY (LEITOR) REFERENCES UTILIZADOR
)

COMMIT TRANSACTION

GO


